# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e38fe5d86a9e56668a2a82a1d749532c1a9e95e0d430cd73db3eebb8e65aad21526f83608884f0c5811536f0033f79bc21b0f570b6c516b4c044f8d16d1cf3a9

test:
  secret_key_base: 3a755fa59d41cfd218874358481ce334dd88f04d3b91989f9d1beafaefce6b4bc61eb39cb6fa0e99547aca6db464ba1c89ad0bacac2f1900398184a84f7e9e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
